config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define recipes default route
  get "recipes", to: "recipes#public"
  get 'shoppings/index'

  # Define routes for recipes
  resources :users do
    resources :foods, only: [:index, :new, :create, :destroy]
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
      resources :shoppings, only:[:index, :show]
    end
    
  end

  # Defines the root path route ("/")
  root "recipes#public"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id

    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy, class_name: 'RecipeFood'

  validates :name, :quantity, :measurement_unit, :price, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy, class_name: 'RecipeFood'

  validates :name, :description, :preparation_time, :cooking_time, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true
end

app/models/shopping_item.rb
class ShoppingItem
  attr_accessor :required_quantity, :food

  def initialize(food, required_quantity)
    @food = food
    @required_quantity = required_quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to user_foods_path
    else
      p @food.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @foods = Food.includes([:user]).where(user_id: current_user.id).order(:name)
  end

  def destroy
    Food.find(params[:id]).destroy
    flash[:success] = 'Food deleted'
    redirect_to user_foods_path
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new; end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'Food added successfully.'
      redirect_to user_recipe_url(@recipe.user, @recipe)
    else
      render 'new'
    end
  end

  def index; end

  def show; end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.find(params[:id])
    @recipe_food.destroy
    redirect_to user_recipe_url(@recipe.user, @recipe)
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      flash[:notice] = 'Food updated successfully.'
      redirect_to user_recipe_url(@recipe.user, @recipe)
    else
      render 'edit'
    end
  end

  def recipe_food_params
    params.permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:success] = 'Recipe created!'
      redirect_to user_recipes_path
    else
      render 'new'
      flash[:error] = 'Recipe not created!'
    end
  end

  def index
    @recipes = Recipe.includes(%i[user recipe_foods]).where(user_id: current_user.id).order('created_at DESC')
    @recipes.each do |recipe|
      recipe.recipe_foods.all.includes([:food]).sort_by { |recipe_food| recipe_food.food.name }
    end
  end

  def show
    @recipe = Recipe.includes([:user]).find(params[:id])
    @recipe_foods = @recipe.recipe_foods.all.includes([:food]).sort_by { |recipe_food| recipe_food.food.name }
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = 'Recipe deleted'
    redirect_to user_recipes_path
  end

  def public
    @public_recipes = Recipe.includes(%i[user recipe_foods]).where(public: true).order('created_at DESC')
    @public_recipes.each do |recipe|
      recipe.recipe_foods.all.includes([:food]).sort_by { |recipe_food| recipe_food.food.name }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :public, :preparation_time, :cooking_time)
  end

  def add_food_view
    @receipt = Receipt.find(params[:receipt_id])
    render 'add_food'
  end
end

app/controllers/shoppings_controller.rb
require_relative '../models/shopping_item'
class ShoppingsController < ApplicationController
  def index
    @shoppings = []
    @recipes = Recipe.all
    @recipes.each do |recipe|
      recipe.recipe_foods.includes([:food]).each do |recipe_food|
        if recipe_food.quantity > recipe_food.food.quantity
          shopping_item = ShoppingItem.new(recipe_food.food, recipe_food.quantity - recipe_food.food.quantity)
          @shoppings << shopping_item
        end
      end
    end

    @total_price = @shoppings.inject(0) do |sum, shopping_item|
      sum + (shopping_item.food.price * shopping_item.required_quantity)
    end
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.all.includes([:food]).sort_by { |recipe_food| recipe_food.food.name }
    @food = Food.includes([:food])
    @total_price = 0
    @recipe_food.each do |fd|
      @total_price += fd.quantity * fd.food.price
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/index.html.erb
<div class="add-f-button">
    <button class="button-af">
      <%= link_to "Add Food", new_user_food_path, {:class => "add_food_button"} %>
    </button>
</div>
<div class='index-container'>
      <table class="table-container">
        <thead>
          <tr>
            <th>Food</th>
            <th>Measurement unit</th>
            <th>Unit price</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td>$ <%= food.price %></td>
            <td>
              <div>
                <%=button_to "Delete", {:controller => :foods, :action => 'destroy', :id => food.id}, :method => :delete, class: 'delete-button' %>
             </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
</div>

app/views/foods/new.html.erb
<div class="page-wrapper">
    <div class='form-wrapper'>
        <h1 class= 'new_title'>Add Food</h1>
        <div class="divider"></div>
        <% if @food.errors.any? %>
            <h2>The following errors prevented the article from saving:</h2>
            <% @food.errors.full_messages.each do |msg| %>
                <%= msg %>
            <% end %>
        <% end %>
        <%= form_with model: @food, url: user_foods_path, method: :post do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :measurement_unit %>
        <%= f.text_field :measurement_unit %>
        <%= f.label :price %>
        <%= f.number_field :price %>
        <%= f.label :quantity %>
        <%= f.number_field :quantity %>
        <%= f.submit "Add Food" %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render '/menu' %>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/create.html.erb
<h1>RecipeFoods#create</h1>
<p>Find me in app/views/recipe_foods/create.html.erb</p>

app/views/recipe_foods/edit.html.erb
<div class="page-wrapper ">
  <div class="form-wrapper">
    <h1> Edit Recipe Food </h1>
    <div class="divider"></div>
    <%= form_with url: user_recipe_recipe_food_path, method: :patch, data: { turbo: false }, local: true do |form| %>
      <% if @recipe_food.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:
          </h2>
          <ul>
            <% @recipe_food.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-item">
        <%= form.label :food, class:"form-label" %><br>
        <%= form.select :food_id, options_for_select(current_user.foods.collect {|food| [food.name, food.id]}, @recipe_food.food_id), { include_blank: true }, class:"form-control" %>
      </div>
      <div class="form-item">
        <%= form.label :quantity, class:"form-label" %>
        <%= form.number_field :quantity, required: true, placeholder: '1',  min: 1, class:"form-control" %>
      </div>
      <div class="form-item">
        <%= form.submit class:"btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipe_foods/index.html.erb
<h1>RecipeFoods#index</h1>
<p>Find me in app/views/recipe_foods/index.html.erb</p>

app/views/recipe_foods/new.html.erb
<div class="page-wrapper">
    <div class="form-wrapper">
        <h1>Add ingredient</h1>
        <div class="divider"></div>
        <%= form_with   url: user_recipe_recipe_foods_path, class:"input-form", data: { turbo: false }  do |f|%>
            <div class="form-item">
            <%= f.label :food, class:"form-label" %><br>
            <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>
            </div>

            <div class="form-item">
            <%= f.label :quantity, class:"form-label" %><br>
            <%= f.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
            </div>

            <div class="form-item">
            <%= f.submit "Create Recipe_Food", class:"btn btn-primary form-control" %>
            </div>
        <%end%>
    </div>
</div>

app/views/recipe_foods/show.html.erb
<h1>RecipeFoods#show</h1>
<p>Find me in app/views/recipe_foods/show.html.erb</p>

app/views/recipe_foods/update.html.erb
<h1> Update Recipe Food </h1>

app/views/recipes/add_food.html.erb
<%= render '/menu' %>

<div class="shoppings">
  <h2 class='shop-title'>Shopping List</h2>
  <div class='flex-shop'>
    <h4 class='amount'>Amount of food items to buy:<span><%= @shoppings.length%></span></h4>
    <h4>Total value of food needed:<span>$<%=@total_price%></span></h4>
  </div>
  <table class='shop-table'>
          <thead>
	@@ -17,9 +17,9 @@
          <tbody>
            <% @shoppings.each do |shopping| %>
              <tr>
                <td><%= shopping.food.name %></td>
                <td><%= shopping.required_quantity %> <%=shopping.food.measurement_unit%></td>
                <td>$<%= shopping.food.price * shopping.required_quantity%></td>
              </tr>
            <% end %>    
          </tbody>

app/views/recipes/cards/_private.html.erb
<div class="recipe">
    <div class="summary">
        <div>
            <% if recipe.public %>
                <span class="public">Public</span>
            <% else %>
                <span class="private">Private</span>
            <% end %>
        </div> 
        <%= link_to recipe.name, user_recipe_path(id: recipe.id, user_id: recipe.user.id) %>
        <%# <h3>By <%= recipe.user.name%> </h3>
        <% if can? :delete, recipe %>
            <%= button_to "Delete", user_recipe_path(recipe.user, recipe.id), method: :delete, class: "btn btn-danger" %>
        <% end %>
    </div>
    <p><%= recipe.description%> </p>
    
</div>

app/views/recipes/cards/_public.html.erb
<div class="public-recipe">
    <div class="info">
        <%= link_to recipe.name, user_recipe_path(id: recipe.id, user_id: recipe.user.id) %>
        <h3>By: <%= recipe.user.name%> </h3>
    </div>
    <div>
    <h5 class="mt-3">Total foods: <%= recipe.recipe_foods.length %> </h5>
        <% sum = 0 %>
        
        <h5>Total price : $ <% recipe.recipe_foods.each do |food| %>
        <% sum += food.food.price %>
        <% end %>
        <%= sum %></h5>
    </div>
</div>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/index.html.erb
<div class="page-wrapper">
  <h1 class="page-heading">Recipe List</h1>
  <%= link_to "Add New Recipe", new_user_recipe_path, class: "btn-add-recipe" %>
  <% @recipes.each do |recipe| %>
    <%= render partial: 'recipes/cards/private', locals: { recipe: recipe, user_id: recipe.id } %>
  <% end %>
  <% if @recipes.empty? %>
    <h1>There are no public recipes to show</h1>
  <% end %>

</div>

app/views/recipes/new.html.erb
<div class="page-wrapper ">
  <div class="form-wrapper">
    <h1 >Add New Recipe</h1>
    <div class="divider"></div>
  <%= form_with model: @recipe, url: user_recipes_url, method: :post do |f| %>
    <div class="form-item">
      <%= f.label :name, class: "form-label" %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name" , class: "form-control" %>
    </div>
    <div class="form-item">
      <%= f.label :preparation_time, class: "form-label" %><br />
        <%= f.text_field :preparation_time, autofocus: true, autocomplete: "preparation_time" ,
          class: "mb-3 form-control" %>
    </div>
    <div class="form-item">
      <%= f.label :cooking_time, class: "form-label" %><br />
        <%= f.text_field :cooking_time, autofocus: true, autocomplete: "cooking_time" %>
    </div>
    <div class="form-item">
      <%= f.label :description, class: "form-label" %><br />
        <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
    </div>
    <div class="form-item">
      <%= f.radio_button :public, true %>
        <%= f.label 'Public' , :public=> 'True' %>
          <%= f.radio_button :public, false %>
            <%= f.label 'Private' , :public=> 'False' %>
    </div>
    <div class="actions">
      <%= f.submit "Add recipe" , class: "btn btn-success" %>
    </div>
    <% end %>

  </div>
</div>

app/views/recipes/public.html.erb
<div class="page-wrapper">
  <h1 class="page-heading">Public Recipe List</h1>
  <% @public_recipes.each do |recipe| %>
    <%= render partial: 'recipes/cards/public', locals: { recipe: recipe, user_id: recipe.id } %>
  <% end %>
  <% if @public_recipes.empty? %>
    <h1>There are no public recipes to show</h1>
  <% end %>

</div>

app/views/recipes/show.html.erb
<div class="page-wrapper">
    <h1 class="page-heading"><%= @recipe.name %></h1>
    <div class="stats">
        <div class="recipe-summary">
            <h4>Preparation Time: <%= @recipe.preparation_time %></h4>
            <h4>Cooking Time: <%= @recipe.cooking_time %></h4>
            <h4>Description: <br><span><%= @recipe.description %></span></h4>
        </div>
        <div>
            <% if @recipe.public %>
                <span class="badge text-bg-warning p-2 px-4">Public</span>
            <% else %>
                <span class="badge text-bg-secondary p-2 px-4">Private</span>
            <% end %>

            <h5 class="mt-3">Total foods: <%= @recipe.recipe_foods.length %> </h5>
            <% sum = 0 %>
                <h5>Total price : $ <% @recipe.recipe_foods.each do |food| %>
                    <% sum += food.food.price %>
                    <% end %>
                    <%= sum %>
                </h5>
        </div>
    </div>

    <div class="action-btns">
        <%= link_to "Generate Shopping List", user_recipe_shopping_path(@recipe.user, @recipe), class: "btn btn-primary" %>
        <% if can? :update, @recipe%>
            <%= link_to "Add Ingredient",new_user_recipe_recipe_food_path(@recipe.user, @recipe.id), class: "btn btn-" %>
        <% end %>
    </div>
    <hr/>
    <table class="table table-striped table-bordered", style="text-align: center; width:100%">
        <% if @recipe.recipe_foods.any? %>
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Food</th>
                    <th>Quantity</th>
                    <th>Value</th>
                    <th>Action</th>
                </tr>
            </thead>
                <tbody>
                    <% @recipe.recipe_foods.each_with_index do |recipe_food, i|%>
                        <tr>
                            <td><%= i+1%></th>
                            <td><%= recipe_food.food.name%></th>
                            <td><%= recipe_food.quantity%> <%= recipe_food.food.measurement_unit  %></td>
                            <td>$<%= recipe_food.quantity* recipe_food.food.price %></td>
                            <td class="mb-3 col-sm-3">
                                <% if can? :manage, @recipe %>
                                    <div class="d-flex justify-content-center gap-2">
                                        <%= link_to "Edit", edit_user_recipe_recipe_food_path(@recipe.user, @recipe.id, recipe_food.id), class: "btn btn-primary" %>
                                        <%= button_to "Delete", user_recipe_recipe_food_path(@recipe.user, @recipe.id, recipe_food.id), method: :delete, class: "btn btn-danger" %>
                                    </div>
                                <% end %>
                            </td>
                        </tr>
                    <%end%>
                </tbody>
        <% end %>
    </table>
</div>

app/views/shoppings/index.heml.erb
<div class="shoppings">
  <h2 class='shop-title'>Shopping List</h2>
  <div class='flex-shop'>
    <h4 class='amount'>Amount of food items to buy:<span><%= @shoppings.length%></span></h4>
    <h4>Total value of food needed:<span>$<%=@total_price%></span></h4>
  </div>
  <table class='shop-table'>
          <thead>
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            <% @shoppings.each do |shopping| %>
              <tr>
                <td><%= shopping.food.name %></td>
                <td><%= shopping.required_quantity %> <%=shopping.food.measurement_unit%></td>
                <td>$<%= shopping.food.price * shopping.required_quantity%></td>
              </tr>
            <% end %>    
          </tbody>
    </table>
</div>

app/views/shoppings/index.html.erb
<div class="shoppings">
  <h2 class='shop-title'>Shopping List</h2>
  <div class='flex-shop'>
    <h4 class='amount'>Amount of food items to buy:<span><%= @shoppings.length%></span></h4>
    <h4>Total value of food needed:<span>$<%=@total_price%></span></h4>
  </div>
  <table class='shop-table'>
          <thead>
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            <% @shoppings.each do |shopping| %>
              <tr>
                <td><%= shopping.food.name %></td>
                <td><%= shopping.required_quantity %> <%=shopping.food.measurement_unit%></td>
                <td>$<%= shopping.food.price * shopping.required_quantity%></td>
              </tr>
            <% end %>    
          </tbody>
    </table>
</div>

app/views/shoppings/show.html.erb
<div class="shoppings">
  <h2 class='shop-title'>Shopping List for <span> <%= @recipe.name %> </h2>
  <div class='flex-shop'>
    <h4 class='amount'>Amount of food items to buy:<span> <%= @recipe_food.length %> </h4>
    <h4>Total price:<span> $ <%= @total_price %></span></h4>
  </div>
  <table class="shop-table">
      <thead>
          <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
          </tr>
      </thead>

      <tbody>
      <% @recipe_food.each do |fd|%>
      <tr>
        <td><%= fd.food.name%></th>
        <td><%= fd.quantity%> <%= fd.food.measurement_unit  %></td>
        <td>$<%= fd.quantity* fd.food.price %></td>
      </tr>

      </tbody>
      </div>
      <%end%>
  </table>
</div>